openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jammacn/jm-weapp/1.0.0
info:
  version: "1.0.0"
  title: jm-weapp-api
  description: 微信小程序系统API
paths:
  /weapp/auth/{code}:
    get:
      description: 查询对应 openid 和 unionid
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthInfo'
  /weapp/decrypt:
    post:
      description: 解密用户信息数据
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncryptedData'
      responses:
        '200':
          description: 结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
  /weapp/token:
    get:
      description: 获取小程序的access_token
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
components:
  schemas:
    AuthInfo:
      type: object
      properties:
        openid:
          type: string
          example: 'root'
        unionid:
          type: string
          example: '123'
      description: 结果信息
    EncryptedData:
      type: object
      properties:
        sessionKey:
          type: string
        iv:
          type: string
        encryptedData:
          type: string
      description: 加密的数据
    UserInfo:
      type: object
      properties:
        openid:
          type: string
          example: 'ognMm0dIGjumkkAuAFCSsu0-Q0Fg'
        unionid:
          type: string
          example: 'oa_ARs19vTALifg9hs4fgdndSyl0'
        nickName:
          type: string
        gender:
          type: integer
          format: int32
        language:
          type: string
        city:
          type: string
        province:
          type: string
        country:
          type: string
        avatarUrl:
          type: string
      description: 结果信息
    AccessToken:
      type: object
      properties:
        token:
          type: string
          example: 'c6gPnazGwjcUlwQjkSaD3Cb1Zz6l_6cLC3RzWLEV0QjImreDxJQJZxVIS'
